services:
  - type: web
    name: taskhive-backend
    env: node
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://taskhive:65BAJNXUf6I0OnqU@taskhive-db.ffbtau8.mongodb.net/taskhive?retryWrites=true&w=majority
      - key: PORT
        value: "5000"
